Update .alacritty.toml Update .zshrc

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -1,6 +1,8 @@
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 
+export PATH="$HOME/.local/bin:$PATH"
+
 # Path to your Oh My Zsh installation.
 export ZSH="$HOME/.oh-my-zsh"
 
@@ -104,6 +106,11 @@ source $ZSH/oh-my-zsh.sh
 
 alias c=chezmoi
 
+# Configure tmux
+if [ -z "$TMUX" ]; then
+    tmux attach -t main || tmux new -s main
+fi
+
 # Configure FZF
 source <(fzf --zsh)
 
@@ -124,6 +131,14 @@ export FZF_ALT_C_OPTS="
   --walker-skip .git,node_modules,target
   --preview 'tree -C {}'"
 
+go() {
+  local dir
+  dir=$(find ~/dev -mindepth 1 -maxdepth 1 -type d | fzf --height=40% --reverse --prompt="~/dev: ")
+  if [[ -n "$dir" ]]; then
+    cd "$dir" || echo "Failed to cd into $dir"
+  fi
+}
+
 # Environment Exports
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
@@ -132,4 +147,7 @@ export NVM_DIR="$HOME/.nvm"
 #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
 export SDKMAN_DIR="$HOME/.sdkman"
 [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
+
+export GH_TOKEN="{{ onepasswordRead "op://Personal/ZSH GitHub Token/password" }}"
+
 
